Name:           ros-jade-pr2-mechanism
Version:        1.8.16
Release:        0%{?dist}
Summary:        ROS pr2_mechanism package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/pr2_mechanism
Source0:        %{name}-%{version}.tar.gz

BuildArch:      noarch

Requires:       ros-jade-pr2-controller-interface
Requires:       ros-jade-pr2-controller-manager
Requires:       ros-jade-pr2-hardware-interface
Requires:       ros-jade-pr2-mechanism-diagnostics
Requires:       ros-jade-pr2-mechanism-model
BuildRequires:  ros-jade-catkin

%description
The pr2_mechanism stack contains the infrastructure to control the PR2 robot in
a hard realtime control loop.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jade/setup.sh" ]; then . "/opt/ros/jade/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/jade" \
        -DCMAKE_PREFIX_PATH="/opt/ros/jade" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jade/setup.sh" ]; then . "/opt/ros/jade/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/jade

%changelog
* Tue Dec 01 2015 Devon Ash <dash@clearpathrobotics.com> - 1.8.16-0
- Autogenerated by Bloom

