Name:           ros-indigo-pr2-controller-manager
Version:        1.8.16
Release:        0%{?dist}
Summary:        ROS pr2_controller_manager package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/pr2_controller_manager
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-indigo-diagnostic-msgs
Requires:       ros-indigo-pluginlib
Requires:       ros-indigo-pr2-controller-interface
Requires:       ros-indigo-pr2-description
Requires:       ros-indigo-pr2-hardware-interface
Requires:       ros-indigo-pr2-mechanism-diagnostics
Requires:       ros-indigo-pr2-mechanism-model
Requires:       ros-indigo-pr2-mechanism-msgs
Requires:       ros-indigo-realtime-tools
Requires:       ros-indigo-roscpp
Requires:       ros-indigo-rosparam
Requires:       ros-indigo-rospy
Requires:       ros-indigo-sensor-msgs
BuildRequires:  ros-indigo-catkin
BuildRequires:  ros-indigo-cmake-modules
BuildRequires:  ros-indigo-diagnostic-msgs
BuildRequires:  ros-indigo-pluginlib
BuildRequires:  ros-indigo-pr2-controller-interface
BuildRequires:  ros-indigo-pr2-description
BuildRequires:  ros-indigo-pr2-hardware-interface
BuildRequires:  ros-indigo-pr2-mechanism-diagnostics
BuildRequires:  ros-indigo-pr2-mechanism-model
BuildRequires:  ros-indigo-pr2-mechanism-msgs
BuildRequires:  ros-indigo-realtime-tools
BuildRequires:  ros-indigo-roscpp
BuildRequires:  ros-indigo-rostest
BuildRequires:  ros-indigo-sensor-msgs

%description
The controller manager (CM) package provides the infrastructure to run
controllers in a hard realtime loop.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Tue Jan 13 2015 Devon Ash <dash@clearpathrobotics.com> - 1.8.16-0
- Autogenerated by Bloom

