%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/noetic/.*$
%global __requires_exclude_from ^/opt/ros/noetic/.*$

Name:           ros-noetic-pr2-mechanism-model
Version:        1.8.18
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS pr2_mechanism_model package

License:        BSD
URL:            http://ros.org/wiki/pr2_mechanism_model
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-noetic-angles
Requires:       ros-noetic-hardware-interface
Requires:       ros-noetic-kdl-parser
Requires:       ros-noetic-pluginlib
Requires:       ros-noetic-pr2-hardware-interface
Requires:       ros-noetic-roscpp
Requires:       ros-noetic-urdf
Requires:       urdfdom-devel
BuildRequires:  ros-noetic-angles
BuildRequires:  ros-noetic-catkin
BuildRequires:  ros-noetic-cmake-modules
BuildRequires:  ros-noetic-hardware-interface >= 0.13.0
BuildRequires:  ros-noetic-kdl-parser
BuildRequires:  ros-noetic-pluginlib
BuildRequires:  ros-noetic-pr2-hardware-interface
BuildRequires:  ros-noetic-roscpp
BuildRequires:  ros-noetic-rostest
BuildRequires:  ros-noetic-rosunit
BuildRequires:  ros-noetic-urdf
BuildRequires:  urdfdom-devel
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%description
This package contains the robot model that is used by the realtime controllers
inside controller manager. This robot model focuses on controlling the robot
mechanism in a realtime control loop, and therefore it only contains the
components of a robot that are relevant in realtime: the robot joints (with
encoders, transmisisons and actuators) and the kinematic/dynamic model of the
robot. The pr2_mechanism_model package is well tested and is released with a
stable API.

%prep
%autosetup

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/noetic/setup.sh" ]; then . "/opt/ros/noetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_LIBDIR="lib" \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/noetic" \
    -DCMAKE_PREFIX_PATH="/opt/ros/noetic" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
    -DCATKIN_BUILD_BINARY_PACKAGE="1" \
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/noetic/setup.sh" ]; then . "/opt/ros/noetic/setup.sh"; fi
%make_install -C obj-%{_target_platform}

%files
/opt/ros/noetic

%changelog
* Wed Dec 02 2020 ROS Orphaned Package Maintainers <ros-orphaned-packages@googlegroups.com> - 1.8.18-1
- Autogenerated by Bloom

